GET http://localhost:8001/artists


###

POST http://localhost:8001/artists
Content-Type: application/json

{
  "notname": "Spice Girls"
}

###

DELETE http://localhost:8001/artists/5a1794096316bf1b89147150

###

PATCH http://localhost:8001/artists/5a176abe9450297b1c736a54
Content-Type: application/json

{
  "name": "I love icecream"
}

###

PATCH http://localhost:8001/artists/5a1768a337d7dc78cca67953
Content-Type: application/json

{
  "name": "Mr Mandle"
}

###

PATCH http://localhost:8001/artists/5a176abe9450297b1c736a54
Content-Type: application/json

{
  "name": ""
}
